runtime: go119
app_engine_apis: true

handlers:
- url: /static
  static_dir: templates/static
  secure: always

- url: /img
  static_dir: templates/img
  secure: always

- url: /css
  static_dir: templates/css
  secure: always

- url: /.*
  script: auto
  secure: always
